package com.example.house_rental_app.navigation

const val ROUTE_LOGIN ="login"
const val ROUTE_REGISTER="register"
const val ROUTE_HOME="home"
const val ROUTE_ADD_PROFILE="Addprofile"
const val ROUTE_VIEW_PROFILE="Viewprofile"
const val ROUTE_UPDATE_PROFILE="Updateprofile"
const val ROUTE_SPLASH="Splash"
const val ROUTE_CONTACTUS="contactus"
const val ROUTE_NEWLOGIN ="new login"
const val ROUTE_NEWREGISTER = "New Register"
const val ROUTE_ALL_LISTINGS = "menuscreens.AllListings"
const val ROUTE_DETAILED_PROPERTY = "property.DetailedProperty"
const val ROUTE_MY_LISTINGS = "menuscreens.MyListings"
const val ROUTE_USER_PROFILE = "menuscreens.UserProfile"
const val ROUTE_ADD_PROPERTY = "menuscreens.AddProperty"
const val ROUTE_MAP = "menuscreens.Map"
const val ROUTE_SETTINGS = "settings.Screen"
const val ROUTE_BOOKING="Booking"
const val ROUTE_CONTACT_LANDLORD = "property.ContactLandlord"